[package]
name = "anput-jobs"
version = "0.12.0"
edition = "2024"
authors = ["Patryk 'PsichiX' Budzynski <psichix@gmail.com>"]
description = "Jobs plugin for Anput ECS"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/PsichiX/anput"
repository = "https://github.com/PsichiX/anput"
documentation = "https://docs.rs/anput-jobs"
readme = "../../README.md"

[features]
deadlock-trace = []
async = ["tokio"]

[dependencies]
tokio = { version = "1.43", features = ["rt"], optional = true }